//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubePlayerEX.Resources.Localisation {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YTPlayerEX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YTPlayerEX() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTubePlayerEX.Resources.Localisation.YTPlayerEX", typeof(YTPlayerEX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Aspect ratio method과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string aspect_ratio_method {
            get {
                return ResourceManager.GetString("aspect_ratio_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string caption_disabled {
            get {
                return ResourceManager.GetString("caption_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closed caption language (only available)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string caption_language {
            get {
                return ResourceManager.GetString("caption_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string display {
            get {
                return ResourceManager.GetString("display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video ID must not be empty!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error_noVideoId {
            get {
                return ResourceManager.GetString("error_noVideoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frame limiter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string frame_limiter {
            get {
                return ResourceManager.GetString("frame_limiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press F11 to exit the full screen.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string fullscreen_entered {
            get {
                return ResourceManager.GetString("fullscreen_entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google Translate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string google_translate {
            get {
                return ResourceManager.GetString("google_translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Graphics과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string graphics {
            get {
                return ResourceManager.GetString("graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letterbox과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string letterbox {
            get {
                return ResourceManager.GetString("letterbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load from video ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string load_from_video_id {
            get {
                return ResourceManager.GetString("load_from_video_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Video과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string load_video {
            get {
                return ResourceManager.GetString("load_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} • {1} subscribers • Click to view channel via external web browser.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string profile_image_tooltip {
            get {
                return ResourceManager.GetString("profile_image_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string screen_mode {
            get {
                return ResourceManager.GetString("screen_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen resolution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string screen_resolution {
            get {
                return ResourceManager.GetString("screen_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected caption: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selected_caption {
            get {
                return ResourceManager.GetString("selected_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected caption: {0} (auto-generated)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selected_caption_auto_gen {
            get {
                return ResourceManager.GetString("selected_caption_auto_gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SFX volume과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string sfx_volume {
            get {
                return ResourceManager.GetString("sfx_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video metadata translate source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string video_metadata_translate_source {
            get {
                return ResourceManager.GetString("video_metadata_translate_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video volume과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string video_volume {
            get {
                return ResourceManager.GetString("video_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} • {1} views과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string videoMetadata_desc {
            get {
                return ResourceManager.GetString("videoMetadata_desc", resourceCulture);
            }
        }
    }
}
